# Generated by Django 5.0.4 on 2024-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high'), (4, 'Critical'), (5, 'immediate fix')], default=2),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Not Selected', 'Не выбрана'), ('Processing...', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Not Selected', max_length=100),
        ),
    ]
